### ISSUE TITLE
Cannot Find Name 'xs'

### ISSUE THREAD

**Issue by sjordan1975** [grtjn/marklogic-typescript-definitions#17]
xs namespace is missing from typings file.

See attached:
![xs namespace](https://cloud.githubusercontent.com/assets/2862727/19548981/7bef76a4-96dc-11e6-9a2f-8b165facd2b6.png)

**Comment by grtjn** [comment]
Thnx!

@christyharagan what do you make of this?

**Comment by christyharagan** [comment]
Yup, again, just bad typing. I'll get a fix in.

**Comment by christyharagan** [comment]
Hang on a second... shouldn't that be:

```ts
fn.QName("")
```

**Comment by sjordan1975** [comment]
@christyharagan Insert a document with the following:

```
declareUpdate();

xdmp.documentInsert('/test.xml', xdmp.unquote("<name>John Doe</name>"))
```

Then run the following query:

`cts.search(cts.elementValueQuery(xs.QName("name")))`

**Comment by christyharagan** [comment]
But I mean, isn't the QName function in the fn namespace, not xs.

xs.QName is the value, whereas fn.QName is the constructor.

**Comment by sjordan1975** [comment]
I'm not sure about that. fn.QName is a function. xs.QName is a value (i think):

https://docs.marklogic.com/fn/qname:

> These built-in functions are XQuery functions defined to operate on qualified name (xs:QName) values. They are defined in XQuery 1.0 and XPath 2.0 Functions and Operators.

**Comment by grtjn** [comment]
fn.QName is a function that takes ns + name. xs.QName is a constructor that takes a string which is local name or prefixed name. Prefix should be known. Then again not sure if xs.QName is avail at all in sjs. I mean how would one declare namespaces..
-------- Oorspronkelijk bericht --------Van: SJordan <notifications@github.com> Datum: 12-04-17  17:15  (GMT+01:00) Aan: grtjn/marklogic-typescript-definitions <marklogic-typescript-definitions@noreply.github.com> Cc: Geert <geert.josten@xs4all.nl>, Comment <comment@noreply.github.com> Onderwerp: Re: [grtjn/marklogic-typescript-definitions] Cannot Find Name 'xs'
  (#17) 
I'm not sure about that. fn.QName is a function. xs.QName is a value (i think):
https://docs.marklogic.com/fn/qname:

These built-in functions are XQuery functions defined to operate on qualified name (xs:QName) values. They are defined in XQuery 1.0 and XPath 2.0 Functions and Operators.


—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/grtjn/marklogic-typescript-definitions","title":"grtjn/marklogic-typescript-definitions","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/grtjn/marklogic-typescript-definitions"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sjordan1975 in #17: I'm not sure about that. fn.QName is a function. xs.QName is a value (i think):\r\n\r\nhttps://docs.marklogic.com/fn/qname:\r\n\r\n\u003e These built-in functions are XQuery functions defined to operate on qualified name (xs:QName) values. They are defined in XQuery 1.0 and XPath 2.0 Functions and Operators."}],"action":{"name":"View Issue","url":"https://github.com/grtjn/marklogic-typescript-definitions/issues/17#issuecomment-293610422"}}}

**Comment by christyharagan** [comment]
Hmmm, you are right. Looking a bit deeper it's a builtin Type Constructor, and our documentation doesn't talk about builtin constructors, hence we don't generate them. 

@grtjn @jmakeig : If we're going to be complete here, we should probably generate *all* xs. type constructors. Any ideas on where we get this? Should our docs be updated?

**Comment by jmakeig** [comment]
> @grtjn @jmakeig : If we're going to be complete here, we should probably generate all xs. type constructors. Any ideas on where we get this? Should our docs be updated?

Yes. We should aim for complete coverage of the entire public API surface area—in both the docs and the typings. I think the first step will be some gap analysis. Is there a classification scheme we can start with?

* Globals
* Namespaces (e.g. `xdmp`, `cts`)
* Built-in types and constructors 
* Built-in functions
* “Proxied” XQuery functions
* Libraries (e.g. JSearch, Optic)

**Comment by grtjn** [comment]
Not sure. Not even sure ML docs divides things in categories at all, other than perhaps by prefix, e.g. xdmp, cts, etc.

What do you mean by built-in?

**Comment by jmakeig** [comment]
“Built-in” means implemented in C++. The end-user doesn’t care where an API is implemented, but the details often matter for how we actually expose things.

**Comment by grtjn** [comment]
Fair point, but the api docs don't bother to describe the built-in types like `xs:QName`. We can only generate typedefs for what is provided in the apidocs. If you can get it added, then it will get included here as well.. :)

**Comment by grtjn** [comment]
This also explains why all xs: types are translated to a primitive or Object
